### ISSUE TITLE
No module named config

### ISSUE THREAD

**Issue by jdimech** [stanford-futuredata/FAST#22]
Just set up a conda environment for FAST.  Trying to run the following command:

$ python run_fp.py -c config.json

Encountering the following error:

Fingerprinting ../parameters/fingerprint/fp_input_CI_TPC_EHZ.json
Traceback (most recent call last):
  File "gen_fp.py", line 5, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

Any ideas what is causing this problem?  Probably a very simple solution.  Thanks.

**Comment by kexinrong** [comment]
Thanks for reporting this! I just pushed a fix for this problem (i was from a previous commit error). Let me know whether the fix works for you.

**Comment by jdimech** [comment]
Thanks for quick reply!  It's a step in the right direction but the program is still generating errors for me:

> Fingerprinting ../parameters/fingerprint/fp_input_CI_TPC_EHZ.json
/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py:172: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type is 'MAD':
/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py:186: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type is 'Zscore':
/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py:192: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type is 'Zscore':
/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py:195: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif type is 'MAD':
Traceback (most recent call last):
  File "MAD.py", line 10, in <module>
    from feature_extractor import *
  File "/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py", line 19, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (/nas/active/ops/nmp/research/jesse/anaconda3/envs/fast/lib/python3.8/site-packages/scipy/misc/__init__.py)
Traceback (most recent call last):
  File "finger_print.py", line 7, in <module>
    from feature_extractor import *
  File "/nas/active/ops/nmp/research/jesse/FAST/fingerprint/feature_extractor.py", line 19, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (/nas/active/ops/nmp/research/jesse/anaconda3/envs/fast/lib/python3.8/site-packages/scipy/misc/__init__.py)
sh: ../data/waveformsTPC/fingerprints/TPC.EHZ.fp: No such file or directory
sh: ../data/waveformsTPC/timestamps/TPC.EHZ.ts: No such file or directory
Traceback (most recent call last):
  File "gen_fp.py", line 60, in <module>
    num_lines = sum(1 for line in open(ts_file))
FileNotFoundError: [Errno 2] No such file or directory: '../data/waveformsTPC/timestamps/ts_Deci5.Pick.19991015130000.CI.TPC.EHZ.sac'
Processing for MAD

I installed the older pre-python 3 version of FAST in a separate conda environment and it seems to work as it should with no errors or warnings. 

Also I think the dependency "sklearn" in requirements.txt should be "scikit-learn", unless I am mistaken?

Thanks again for your help

**Comment by kexinrong** [comment]
It seems that the imresize function was [removed](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.misc.imresize.html) in scipy 1.3.0. You might want to downgrade scipy to an earlier version, or use the new function instead.   For reference, I was testing using scipy version 1.1.0.
